In [6]:
import pandas as pd
import numpy as np

In [7]:
db51 = pd.read_csv('channel_cat.csv', sep=';')

db80 = pd.read_csv('channel_cat_80.csv', sep=';')

In [8]:
comp_db = pd.merge(db51, db80, how='inner', left_on='channel', right_on='channel')
comp_db

,Unnamed: 0_x,channel,main_cat_x,Unnamed: 0_y,main_cat_y
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,Travel,0,Travel
1,1,UC--2EbuIuBOGgGqPiJxi3rg,People,1,People
2,2,UC--3ozenTzry39-xMqAPQlw,Education,2,Education
3,3,UC--6E6EpybocdaNlPhvK_9A,People,3,People
4,4,UC--70ql_IxJmhmqXqrkJrWQ,People,4,People
...,...,...,...,...,...
88488,88488,UCzzqd0yx7h1PuC3KJVqeJgw,People,88488,People
88489,88489,UCzzsKg4jPGBL05t2w3HfHBA,Mixed,88489,Mixed
88490,88490,UCzzt-UNlRHbEFY3rEpFpuXw,Entertainment,88490,Entertainment
88491,88491,UCzzzPMh9fZHxc7gxPRB2LHQ,Mixed,88491,Mixed
88492,88492,UCzzzZ3-icktxbC3j7hkWqRw,How to & Style,88492,How to & Style

In [9]:
conditions = [(comp_db['main_cat_x']==comp_db['main_cat_y']), 
              (comp_db['main_cat_x']!=comp_db['main_cat_y'])]

values = [True, False]

comp_db['same'] = np.select(conditions, values)

comp_db

,Unnamed: 0_x,channel,main_cat_x,Unnamed: 0_y,main_cat_y,same
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,Travel,0,Travel,1
1,1,UC--2EbuIuBOGgGqPiJxi3rg,People,1,People,1
2,2,UC--3ozenTzry39-xMqAPQlw,Education,2,Education,1
3,3,UC--6E6EpybocdaNlPhvK_9A,People,3,People,1
4,4,UC--70ql_IxJmhmqXqrkJrWQ,People,4,People,1
...,...,...,...,...,...,...
88488,88488,UCzzqd0yx7h1PuC3KJVqeJgw,People,88488,People,1
88489,88489,UCzzsKg4jPGBL05t2w3HfHBA,Mixed,88489,Mixed,1
88490,88490,UCzzt-UNlRHbEFY3rEpFpuXw,Entertainment,88490,Entertainment,1
88491,88491,UCzzzPMh9fZHxc7gxPRB2LHQ,Mixed,88491,Mixed,1
88492,88492,UCzzzZ3-icktxbC3j7hkWqRw,How to & Style,88492,How to & Style,1

In [10]:
comp_db[comp_db['same']==0]

,Unnamed: 0_x,channel,main_cat_x,Unnamed: 0_y,main_cat_y,same
18,18,UC--mO_MwJryZfcxeaefzetg,Entertainment,18,Mixed,0
57,57,UC-10uJUkzxSXa9sEtV67YcA,Gaming,57,Mixed,0
59,59,UC-1CvlOVGAUzvffUyLOQ0hA,Autos & Vehicles,59,Mixed,0
63,63,UC-1TUi3OPc2jSVWLNM2ARwg,Entertainment,63,Mixed,0
70,70,UC-1onbNXd_l9jbbld21EOGw,Film & Animation,70,Mixed,0
...,...,...,...,...,...,...
88415,88415,UCzwCkeBYDKAR7jpk986MYtw,Gaming,88415,Mixed,0
88435,88435,UCzx9exbj1Zoh51o2Sr5rxBQ,Gaming,88435,Mixed,0
88447,88447,UCzxztcLww-jPvE5QbFC3n0g,Entertainment,88447,Mixed,0
88470,88470,UCzz0tForkMrJgZPAC58gakg,Entertainment,88470,Mixed,0
88477,88477,UCzzSPRyMYUw6IGueHr1K0Jg,Gaming,88477,Mixed,0