## Additional channel selection

As mentionned in our paper, we looked into channels whose main video genre is not associated with traditionnal media (films and animation, music, news and politics, and sports). For our analysis, we removed channels linked to these topics

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 100)

In [3]:
db_week=pd.read_csv('weekly_uploads_cat_completed.csv', sep=';')
db_week.head()

,week,channel,...1,before_updates,category,id,id_0,cat_people,cat_ent,cat_educ,...,cat_travel,cat_game,cat_science,cat_activ,cat_pet,cat_film,cat_music,cat_news,cat_sport,cat_unknown
0,2016-33,UC--24Q3_ZQeFmgJE-Um5QZQ,0.0,1.0,Travel & Events,1.0,1,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016-33,UC--2EbuIuBOGgGqPiJxi3rg,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-33,UC--3ozenTzry39-xMqAPQlw,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-33,UC--6E6EpybocdaNlPhvK_9A,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-33,UC--70ql_IxJmhmqXqrkJrWQ,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
db=db_week[['week', 'channel', 'id_0']].copy()
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5720550 entries, 0 to 5720549
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   week     object
 1   channel  object
 2   id_0     int64
dtypes: int64(1), object(2)
memory usage: 130.9+ MB

In [5]:
db=db.groupby(['channel', 'week'], as_index=False)['id_0'].sum()
db

                          channel     week  id_0
0        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-33     1
1        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-34     1
2        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-35     1
3        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-36     1
4        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-37     1
...                           ...      ...   ...
5575054  UCzzzZ3-icktxbC3j7hkWqRw  2017-39     0
5575055  UCzzzZ3-icktxbC3j7hkWqRw  2017-40     0
5575056  UCzzzZ3-icktxbC3j7hkWqRw  2017-41     0
5575057  UCzzzZ3-icktxbC3j7hkWqRw  2017-42     0
5575058  UCzzzZ3-icktxbC3j7hkWqRw  2017-43     0

[5575059 rows x 3 columns]

In [6]:
db['week']=db['week'].replace('2017-00', '2016-52')

In [7]:
db=db.groupby(['channel', 'week'], as_index=False)['id_0'].sum()
db

                          channel     week  id_0
0        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-33     1
1        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-34     1
2        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-35     1
3        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-36     1
4        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-37     1
...                           ...      ...   ...
5575054  UCzzzZ3-icktxbC3j7hkWqRw  2017-39     0
5575055  UCzzzZ3-icktxbC3j7hkWqRw  2017-40     0
5575056  UCzzzZ3-icktxbC3j7hkWqRw  2017-41     0
5575057  UCzzzZ3-icktxbC3j7hkWqRw  2017-42     0
5575058  UCzzzZ3-icktxbC3j7hkWqRw  2017-43     0

[5575059 rows x 3 columns]

In [8]:
db['week'].nunique()

63

### Removing channels not in greenlighted categories

In [9]:
db_chan_cat=pd.read_csv('channel_cat_51.csv', sep=';')
db_chan_cat

       Unnamed: 0                   channel        main_cat
0               0  UC--24Q3_ZQeFmgJE-Um5QZQ          Travel
1               1  UC--2EbuIuBOGgGqPiJxi3rg          People
2               2  UC--3ozenTzry39-xMqAPQlw       Education
3               3  UC--6E6EpybocdaNlPhvK_9A          People
4               4  UC--70ql_IxJmhmqXqrkJrWQ          People
...           ...                       ...             ...
88488       88488  UCzzqd0yx7h1PuC3KJVqeJgw          People
88489       88489  UCzzsKg4jPGBL05t2w3HfHBA           Mixed
88490       88490  UCzzt-UNlRHbEFY3rEpFpuXw   Entertainment
88491       88491  UCzzzPMh9fZHxc7gxPRB2LHQ           Mixed
88492       88492  UCzzzZ3-icktxbC3j7hkWqRw  How to & Style

[88493 rows x 3 columns]

In [10]:
db=pd.merge(db, db_chan_cat, how='left', left_on='channel', right_on='channel')
db

                          channel     week  id_0  Unnamed: 0        main_cat
0        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-33     1           0          Travel
1        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-34     1           0          Travel
2        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-35     1           0          Travel
3        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-36     1           0          Travel
4        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-37     1           0          Travel
...                           ...      ...   ...         ...             ...
5575054  UCzzzZ3-icktxbC3j7hkWqRw  2017-39     0       88492  How to & Style
5575055  UCzzzZ3-icktxbC3j7hkWqRw  2017-40     0       88492  How to & Style
5575056  UCzzzZ3-icktxbC3j7hkWqRw  2017-41     0       88492  How to & Style
5575057  UCzzzZ3-icktxbC3j7hkWqRw  2017-42     0       88492  How to & Style
5575058  UCzzzZ3-icktxbC3j7hkWqRw  2017-43     0       88492  How to & Style

[5575059 rows x 5 columns]

In [11]:
db=db[(db['main_cat']!='Music') & (db['main_cat']!='Film & Animation')
      & (db['main_cat']!='News & Politics') & (db['main_cat']!='Sports')  
      & (db['main_cat']!='Unknown')]
db

                          channel     week  id_0  Unnamed: 0        main_cat
0        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-33     1           0          Travel
1        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-34     1           0          Travel
2        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-35     1           0          Travel
3        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-36     1           0          Travel
4        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-37     1           0          Travel
...                           ...      ...   ...         ...             ...
5575054  UCzzzZ3-icktxbC3j7hkWqRw  2017-39     0       88492  How to & Style
5575055  UCzzzZ3-icktxbC3j7hkWqRw  2017-40     0       88492  How to & Style
5575056  UCzzzZ3-icktxbC3j7hkWqRw  2017-41     0       88492  How to & Style
5575057  UCzzzZ3-icktxbC3j7hkWqRw  2017-42     0       88492  How to & Style
5575058  UCzzzZ3-icktxbC3j7hkWqRw  2017-43     0       88492  How to & Style

[4087692 rows x 5 columns]

In [12]:
db=db.drop(['Unnamed: 0'], axis=1)

In [13]:
db['channel'].nunique()

64884

In [14]:
condition=[(db["week"]>="2017-12"),
          (db["week"]<"2017-12")]
value=[0, 1]
db["before_update"]=np.select(condition, value)
db

,channel,week,id_0,main_cat,before_update
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1
...,...,...,...,...,...
5575054,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0
5575055,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0
5575056,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0
5575057,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0
5575058,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0

### removing channels not active prior moderation update

In [15]:
db_before=db[db['before_update']==1]

In [16]:
test=db_before.groupby('channel', as_index=False)['id_0'].sum()
test

                        channel  id_0
0      UC--24Q3_ZQeFmgJE-Um5QZQ    31
1      UC--2EbuIuBOGgGqPiJxi3rg     5
2      UC--3ozenTzry39-xMqAPQlw     7
3      UC--6E6EpybocdaNlPhvK_9A     4
4      UC--70ql_IxJmhmqXqrkJrWQ    33
...                         ...   ...
64879  UCzzqd0yx7h1PuC3KJVqeJgw    77
64880  UCzzsKg4jPGBL05t2w3HfHBA     0
64881  UCzzt-UNlRHbEFY3rEpFpuXw    11
64882  UCzzzPMh9fZHxc7gxPRB2LHQ   162
64883  UCzzzZ3-icktxbC3j7hkWqRw     1

[64884 rows x 2 columns]

In [17]:
test=test[test['id_0']==0]
test

                        channel  id_0
12     UC--g_wJaqDjFx57RPrtSpow     0
23     UC-0ArFZnd6UrtWM7BDlt4RA     0
37     UC-1-apD4M2ZlCoJG-HWzCgw     0
45     UC-1W6GKASWrqZfK45zFLapg     0
59     UC-2Pz4YPcFTRSq1L83e4xOQ     0
...                         ...   ...
64852  UCzyMqWhjqFkxxdM6C3UYsOg     0
64854  UCzybXLxv08IApdjdN0mJhEg     0
64866  UCzzHicLcWJP2jagxpqebzsA     0
64875  UCzzbaQY1nPim5yroAjtXRTw     0
64880  UCzzsKg4jPGBL05t2w3HfHBA     0

[7250 rows x 2 columns]

In [18]:
unique_before=test['channel'].unique()
len(unique_before)

7250

In [19]:
unique_total=db['channel'].unique()
len(unique_total)

64884

In [20]:
db=db[~db["channel"].isin(unique_before)]
db

,channel,week,id_0,main_cat,before_update
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1
...,...,...,...,...,...
5575054,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0
5575055,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0
5575056,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0
5575057,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0
5575058,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0

In [21]:
db['channel'].nunique()

57634

In [22]:
db['week'].nunique()

63

In [23]:
max(db['id_0'])

5830

### Channel's average audience size before moderation update

We calculate the average number of followers for each channel. This enables us to estimate our model with the subscribers number brackets.

In [24]:
db_timeseries=pd.read_csv("timeseries_cleaned.csv", sep=';')
db_timeseries

,Unnamed: 0,channel,category,datetime,views,delta_views,subs,delta_subs,videos,delta_videos,activity,week
0,0,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-03 00:00:00,2.024946e+05,0.000000,650.222222,0.000000,5,0,3,2017-27
1,1,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-10 00:00:00,3.940857e+05,191591.111111,1046.000000,395.777778,6,1,1,2017-28
2,2,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-17 00:00:00,8.353938e+05,441308.083333,1501.500000,455.500000,6,0,1,2017-29
3,3,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-24 00:00:00,1.104577e+06,269183.250000,1750.000000,248.500000,6,0,0,2017-30
4,4,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-31 00:00:00,1.284406e+06,179828.600000,2008.300000,258.300000,6,0,0,2017-31
...,...,...,...,...,...,...,...,...,...,...,...,...
13878018,18872455,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-02 23:00:00,3.167820e+03,159.564033,1490.027778,0.000000,0,0,0,2018-48
13878019,18872456,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-09 23:00:00,3.327384e+03,159.564033,1484.509259,0.000000,0,0,0,2018-49
13878020,18872457,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-16 23:00:00,3.486948e+03,159.564033,1473.620370,0.000000,0,0,0,2018-50
13878021,18872458,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-23 23:00:00,3.646512e+03,159.564033,1470.013889,0.000000,0,0,0,2018-51
13878022,18872459,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-30 23:00:00,3.806076e+03,159.564033,1717.935185,247.921296,0,0,0,2018-52

In [26]:
db_weekly=pd.merge(db, db_timeseries, how='left', left_on=['channel', 'week'], right_on=['channel', 'week'])

In [27]:
db_weekly

,channel,week,id_0,main_cat,before_update,Unnamed: 0,category,datetime,views,delta_views,subs,delta_subs,videos,delta_videos,activity
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1928794.0,Travel & Events,2016-08-15 00:00:00,69982.000,2381.750,1530.750,22.125,31.0,1.0,2.0
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1928795.0,Travel & Events,2016-08-22 00:00:00,72663.125,2681.125,1558.625,27.875,32.0,1.0,2.0
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1928796.0,Travel & Events,2016-08-29 00:00:00,75093.000,2429.875,1591.000,32.375,33.0,1.0,2.0
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1928797.0,Travel & Events,2016-09-05 00:00:00,77511.500,2418.500,1621.625,30.625,34.0,1.0,2.0
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1928798.0,Travel & Events,2016-09-12 00:00:00,80095.000,2583.500,1650.750,29.125,35.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3630937,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0,3932834.0,Howto & Style,2017-09-25 00:00:00,3996798.000,50051.750,53927.000,413.875,37.0,0.0,0.0
3630938,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0,3932835.0,Howto & Style,2017-10-02 00:00:00,4043154.625,46356.625,54334.750,407.750,37.0,0.0,0.0
3630939,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0,3932836.0,Howto & Style,2017-10-09 00:00:00,4095563.000,52408.375,54783.000,448.250,37.0,0.0,0.0
3630940,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0,3932837.0,Howto & Style,2017-10-16 00:00:00,4149823.125,54260.125,55273.625,490.625,37.0,0.0,0.0
3630941,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0,3932838.0,Howto & Style,2017-10-23 00:00:00,4202399.000,52575.875,55758.000,484.375,37.0,0.0,0.0

In [28]:
max(db_weekly['id_0'])

5830

In [29]:
db_average=db_weekly[db_weekly['before_update']==1]
db_average

,channel,week,id_0,main_cat,before_update,Unnamed: 0,category,datetime,views,delta_views,subs,delta_subs,videos,delta_videos,activity
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1928794.0,Travel & Events,2016-08-15 00:00:00,6.998200e+04,2381.750000,1530.750000,22.125000,31.0,1.0,2.0
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1928795.0,Travel & Events,2016-08-22 00:00:00,7.266312e+04,2681.125000,1558.625000,27.875000,32.0,1.0,2.0
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1928796.0,Travel & Events,2016-08-29 00:00:00,7.509300e+04,2429.875000,1591.000000,32.375000,33.0,1.0,2.0
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1928797.0,Travel & Events,2016-09-05 00:00:00,7.751150e+04,2418.500000,1621.625000,30.625000,34.0,1.0,2.0
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1928798.0,Travel & Events,2016-09-12 00:00:00,8.009500e+04,2583.500000,1650.750000,29.125000,35.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3630905,UCzzzZ3-icktxbC3j7hkWqRw,2017-07,0,How to & Style,1,3932802.0,Howto & Style,2017-02-12 23:00:00,2.016087e+06,137452.875000,30222.833333,2548.000000,29.0,0.0,0.0
3630906,UCzzzZ3-icktxbC3j7hkWqRw,2017-08,0,How to & Style,1,3932803.0,Howto & Style,2017-02-19 23:00:00,2.101185e+06,85098.375000,31453.098958,1230.265625,29.0,0.0,0.0
3630907,UCzzzZ3-icktxbC3j7hkWqRw,2017-09,0,How to & Style,1,3932804.0,Howto & Style,2017-02-26 23:00:00,2.166973e+06,65788.218750,32404.369792,951.270833,29.0,0.0,0.0
3630908,UCzzzZ3-icktxbC3j7hkWqRw,2017-10,0,How to & Style,1,3932805.0,Howto & Style,2017-03-05 23:00:00,2.233568e+06,66594.317708,33465.052083,1060.682292,29.0,0.0,0.0
3630909,UCzzzZ3-icktxbC3j7hkWqRw,2017-11,0,How to & Style,1,3932806.0,Howto & Style,2017-03-12 23:00:00,2.300416e+06,66848.463542,34490.848958,1025.796875,29.0,0.0,0.0

In [30]:
db_average=db_average.groupby('channel', as_index=False, dropna=False)['subs'].mean().round(0)
db_average

                        channel     subs
0      UC--24Q3_ZQeFmgJE-Um5QZQ   1873.0
1      UC--2EbuIuBOGgGqPiJxi3rg   4363.0
2      UC--3ozenTzry39-xMqAPQlw  67839.0
3      UC--6E6EpybocdaNlPhvK_9A  31732.0
4      UC--70ql_IxJmhmqXqrkJrWQ  83026.0
...                         ...      ...
57629  UCzzoJY_ln_StRVdrRX1_ftg    357.0
57630  UCzzqd0yx7h1PuC3KJVqeJgw    557.0
57631  UCzzt-UNlRHbEFY3rEpFpuXw  21007.0
57632  UCzzzPMh9fZHxc7gxPRB2LHQ  12932.0
57633  UCzzzZ3-icktxbC3j7hkWqRw  18966.0

[57634 rows x 2 columns]

In [31]:
final=pd.merge(db, db_average, how='left', left_on='channel', right_on='channel')
final

,channel,week,id_0,main_cat,before_update,subs
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1873.0
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1873.0
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1873.0
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1873.0
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1873.0
...,...,...,...,...,...,...
3630937,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0,18966.0
3630938,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0,18966.0
3630939,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0,18966.0
3630940,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0,18966.0
3630941,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0,18966.0

In [32]:
max(final['id_0'])

5830

In [33]:
test=final[final['subs'].isna()]
test

,channel,week,id_0,main_cat,before_update,subs
315,UC--7oyGW0N7fMf164-ZXljQ,2016-33,0,People,1,NaN
316,UC--7oyGW0N7fMf164-ZXljQ,2016-34,1,People,1,NaN
317,UC--7oyGW0N7fMf164-ZXljQ,2016-35,0,People,1,NaN
318,UC--7oyGW0N7fMf164-ZXljQ,2016-36,0,People,1,NaN
319,UC--7oyGW0N7fMf164-ZXljQ,2016-37,0,People,1,NaN
...,...,...,...,...,...,...
3629047,UCzxbp5h6lUD8yqF4MH-ICuQ,2017-39,1,Science & Technology,0,NaN
3629048,UCzxbp5h6lUD8yqF4MH-ICuQ,2017-40,1,Science & Technology,0,NaN
3629049,UCzxbp5h6lUD8yqF4MH-ICuQ,2017-41,1,Science & Technology,0,NaN
3629050,UCzxbp5h6lUD8yqF4MH-ICuQ,2017-42,1,Science & Technology,0,NaN
3629051,UCzxbp5h6lUD8yqF4MH-ICuQ,2017-43,2,Science & Technology,0,NaN

In [34]:
test['channel'].nunique()

4099

In [35]:
final=final[~final['subs'].isna()]
final

,channel,week,id_0,main_cat,before_update,subs
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1873.0
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1873.0
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1873.0
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1873.0
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1873.0
...,...,...,...,...,...,...
3630937,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0,18966.0
3630938,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0,18966.0
3630939,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0,18966.0
3630940,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0,18966.0
3630941,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0,18966.0

In [36]:
final['channel'].nunique()

53535

In [37]:
final.to_csv('weekly_uploads_cat_completed.csv', sep=';')