## Treatment and control groups for selected channels

The examined intervention targeted specific content: "videos that are perceived to be hateful or inflammatory” and “content that is harassing or attacking people based on their race, religion, gender or similar categories".
To estimate the effect on creators’ content supply, we categorised channels based on the topic of their published videos before the implementation of the moderation. The categorisation relied on keyword matching. A total of 96 words and expressions based on this condition  was generated. 
The keyword matching was done on the title, description and tags for videos published before the March 2017’s moderation update (n videos = 2,742,395).

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
db_video=pd.read_csv('video_database_per_period_selected.csv', sep=';')
db_video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11845978 entries, 0 to 11845977
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0.1    int64
 1   Unnamed: 0      int64
 2   category        object
 3   channel         object
 4   date_crawled    object
 5   description     object
 6   id              object
 7   duration        int64
 8   tags            object
 9   title           object
 10  upload          object
 11  week            object
 12  before_updates  float64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.1+ GB

In [3]:
db_chan=pd.read_csv('weekly_uploads_cat_completed.csv', sep=';')
chan=db_chan['channel'].unique().tolist()
len(chan)

53535

In [4]:
db_video=db_video[db_video['channel'].isin(chan)]
db_video.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7807776 entries, 141 to 11845922
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0.1    int64
 1   Unnamed: 0      int64
 2   category        object
 3   channel         object
 4   date_crawled    object
 5   description     object
 6   id              object
 7   duration        int64
 8   tags            object
 9   title           object
 10  upload          object
 11  week            object
 12  before_updates  float64
dtypes: float64(1), int64(3), object(9)
memory usage: 834.0+ MB

In [5]:
out=pd.read_csv('outliers_995.csv', sep=';')
chan=out['channel'].unique().tolist()
len(chan)

1676

In [18]:
db_video=db_video[~db_video['channel'].isin(chan)]
db_video.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5596628 entries, 141 to 11845922
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0.1    int64
 1   Unnamed: 0      int64
 2   category        object
 3   channel         object
 4   date_crawled    object
 5   description     object
 6   id              object
 7   duration        int64
 8   tags            object
 9   title           object
 10  upload          object
 11  week            object
 12  before_updates  float64
dtypes: float64(1), int64(3), object(9)
memory usage: 597.8+ MB

In [19]:
max(db_video['week'])

'2017-43'

In [20]:
db_video['channel'].nunique()

51859

## Selecting before update videos

In [21]:
db_before=db_video[db_video['before_updates']==1]

In [22]:
db_before.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2742395 entries, 363 to 11845922
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0.1    int64
 1   Unnamed: 0      int64
 2   category        object
 3   channel         object
 4   date_crawled    object
 5   description     object
 6   id              object
 7   duration        int64
 8   tags            object
 9   title           object
 10  upload          object
 11  week            object
 12  before_updates  float64
dtypes: float64(1), int64(3), object(9)
memory usage: 292.9+ MB

In [23]:
db_before['channel'].nunique()

51859

In [24]:
db_before['description'].isna().sum()

78607

In [25]:
db_before['tags'].isna().sum()

235058

In [26]:
db_before[['description','tags']].isna().all(axis=1).sum()

45071

In [27]:
db_before['id'].count()

2742395

## Title, description and tags analysis

In [28]:
bad_words=[]

path = 'adalytics_cleaned_2026.txt'

with open(path, 'r') as fp:
    for line in fp:
        x = line[:-1]
        # add current item to the list
        bad_words.append(x)

bad_words

['flash mob',
 'violent crim',
 'handgun',
 'sex offens',
 'stab',
 'school shoot',
 'fetish',
 'medical marijuana',
 'military act',
 'traffick',
 'al qaeda',
 'alcohol depend',
 'war-ravag',
 'march',
 'racial stereotyp',
 'fentanyl',
 'anwar al-awlaki',
 'nuke',
 'dick',
 'deadly blast',
 'breast',
 'recreational drug',
 'scum',
 'sexual act',
 'football party shoot',
 'racial profil',
 'celebrity death',
 'curfew',
 'kidnap',
 'mob',
 'bomb attack',
 'addictive drug',
 'breonna',
 'stripper',
 'pornhub',
 'multiple death',
 'officer-involved shoot',
 'blm',
 'weaponri',
 'fatal',
 'birth control',
 'bombing suspect',
 'charlottesville r',
 'pellet gun',
 'violent rhetor',
 'london attack',
 'dangerous drug',
 'hiv/aid',
 'war',
 'whore',
 'nuclear attack',
 'pharmaceutical drug',
 'knife attack',
 'benghazi',
 'fatal crash',
 'automatic weapon',
 'white supremac',
 'vandal',
 'enemy combat',
 'abusive relationship',
 'upskirt',
 'death tol',
 'dead',
 'nuclear strik',
 'child pornographi',
 'racial conflict',
 'philando castil',
 'coronavirus death r',
 'terror campaign',
 'jihadi',
 'crude bomb',
 'harassment alleg',
 'wwi',
 'islamist rebel',
 'gunman',
 'weapon',
 'march for lif',
 'ransomwar',
 'several dead',
 'orlando shoot',
 'coupl',
 'domestic terror',
 'tiananmen',
 'racial bia',
 'civil war',
 'alcohol consumpt',
 'menstrual',
 'truck attack',
 'ben carson',
 'repress',
 'anti semit',
 'human traffick',
 'nato',
 'reproductive health',
 'anal',
 'waterboard',
 'deadly attack',
 'picket',
 'began shoot',
 'military-styl',
 'tortur',
 'isil',
 'extremist group',
 'homicid',
 'incest',
 'hostage situ',
 'racist rhetor',
 'racist',
 'shoots up',
 'injur',
 'pubic',
 'ankara',
 'abuse alleg',
 'the bill is dead',
 'drunk driv',
 'martial law',
 'extremist',
 'florida school shoot',
 'failed drug test',
 'child porn',
 'coronavirus death tol',
 'star war',
 'attack helicopt',
 'coon',
 'suicid',
 'pregnant',
 'taliban attack',
 'sexually assault',
 'peace talk',
 'deadly bomb',
 'gun rampag',
 'hanukkah stab',
 'pimp',
 'sexist com',
 'holocaust',
 'ass',
 'chemical weapon',
 'shooting in hall',
 'trade war',
 'driving under the influ',
 'race war',
 'warhead',
 'abductor',
 "friday's attack",
 'syria war',
 'bdsm',
 'rally area',
 'alcohol',
 'terror attack',
 'brutal',
 'islamist militia',
 'naked photograph',
 'suspected attack',
 'death sent',
 'axe',
 'explos',
 'vegas shoot',
 'sex abus',
 'protestor',
 'racially charg',
 'violenc',
 'nazism',
 'james foley',
 '911 attack',
 'gun bil',
 'non-combat',
 'weed',
 'execut',
 'neo nazi',
 'lethal inject',
 'sexual harass',
 'massive attack',
 'alt-right',
 'racially motiv',
 'cartel',
 'internet blackout',
 'several people dead',
 'crack cocain',
 'korean nuclear',
 'kkk',
 'war and conflict',
 'pipe bomb',
 'ww2',
 'incitement to',
 'an alcohol',
 'murder',
 'orlando',
 'shit',
 'semen',
 'sarin',
 'orlando puls',
 'deadly shoot',
 'christchurch shoot',
 'injured in shoot',
 'terrorist incid',
 'al-shabaab',
 'charlie hebdo massacr',
 'acts of terror',
 'nuclear weapon',
 'activist',
 'racial attack',
 'korean war',
 'food addict',
 'bin laden',
 'airport attack',
 'mosque shoot',
 'aids/hiv',
 'death penalti',
 'national rifle associ',
 'crack',
 'gun on himself',
 'hooker',
 'gun crim',
 'militia',
 'pedo',
 'arsenic',
 'drug cartel',
 'strike',
 'revolt',
 'drug traffick',
 'mosque attack',
 'nude',
 'behead',
 'drunk',
 'bomb squad',
 'in shoot',
 'military intervent',
 'shootout',
 'sexual off',
 'menstruat',
 'fuck',
 'sexism',
 'bastard',
 'drinking alcohol',
 'hong kong protest',
 'buying drug',
 'charlie hebdo',
 'death rat',
 'oklahoma city bomb',
 'time bomb',
 'nitrous',
 'erectile dysfunct',
 'fatal shoot',
 'gunpoint',
 'ak47',
 'joint',
 'sexual misconduct',
 'wounded children',
 'spic',
 'assault-style weapon',
 'london bridge attack',
 'nazi',
 'sexual com',
 'recruit',
 'reproduct',
 'meth',
 'firearm',
 'shoot',
 'charlie hebdo attack',
 'lgbtq',
 'executive ord',
 'retard',
 'afghanistan',
 'sperm',
 'anti-terror',
 'korea nuclear',
 'rebellion',
 'mammogram',
 'addict',
 'civil unrest',
 'nuclear war',
 'soldiers shot',
 'nuclear threat',
 'daesh',
 'drug abus',
 'harass',
 'blackout',
 'password',
 'annexation of crimea',
 'racial hatr',
 'goddamn',
 'hundreds injur',
 'edward snowden',
 'bleed',
 'pregnanc',
 'infertil',
 'battlefield',
 'gunman who kil',
 'sex offend',
 'aleppo',
 'aryan',
 'active shoot',
 'lone gunman',
 'terror tact',
 'laser weapon',
 'military styl',
 'kobani',
 'slaughterhous',
 'bombs explod',
 'nigger',
 'deadly virus',
 'terror',
 'opium',
 'far-right group',
 'alcoholics anonym',
 'racial harass',
 'wounded in shoot',
 'illegal drug',
 'crystal meth',
 'sexist',
 'cock',
 'sexual abus',
 'warship',
 'abduct',
 'wwii',
 'assassin',
 'george floyd',
 'yuen long attack',
 'unwanted sexu',
 'gunman kil',
 'bomblet',
 'three dead',
 'september 11th attack',
 'shooting peopl',
 'al shabaab',
 'nuclear deterr',
 'bombing raid',
 'high on drug',
 'coronavirus death',
 'tit',
 'planned parenthood',
 'hate speech',
 'boko haram',
 'shot to death',
 'fatally shoot',
 'machinegun',
 'pro-lif',
 'deadliest mass shoot',
 'scrotum',
 'embryo',
 'easter sunday attack',
 'pearl harbor',
 'fighter bomb',
 'illicit drug',
 'sexually explicit',
 'pelvic',
 'boston marathon',
 'prostitut',
 'death threat',
 'taliban',
 'boston bomb',
 'combat',
 'boston marathon bomb',
 'occupy mov',
 'racist slur',
 'sexual pleasur',
 'terror victim',
 'alcohol addict',
 'a drunk',
 'dwi',
 'arson',
 'incest/abuse support',
 'orlando nightclub',
 'cyberattack',
 'hezbollah',
 'extort',
 'gun battl',
 'united nations peacekeep',
 'racially insensit',
 'terrorist propaganda',
 'misogynist',
 'sexual natur',
 'sept 11',
 'fake bomb',
 'combat oper',
 'crap',
 'hump',
 'sex discrimin',
 'fatal arrest',
 'san bernardino',
 'hate group',
 'pepper spray',
 'slut',
 'plan b',
 'shoot man',
 'september 11',
 'ransom',
 'plotting to bomb',
 'shoot-out',
 'opioid epidem',
 'car bomb',
 'self-radicalis',
 'nuclear accid',
 'heroin',
 'bomb dispos',
 'gun viol',
 'white supremacist',
 'nuclear pow',
 'rebel-held',
 'brutal crackdown',
 'brothel',
 'oppress',
 'syrian rebel',
 'right-wing extremist',
 'fatally shot',
 'homemade bomb',
 'nuclear conflict',
 'bullshit',
 'pornograph',
 'nuclear missil',
 'terroristic threat',
 'hostage-tak',
 'racial slur',
 'incite hatr',
 'drug deal',
 'sexual assault',
 'drug',
 'flight 93',
 'ak-47',
 'genocid',
 'anti-fascist',
 'islamist terror',
 'injuring dozen',
 'antifa',
 'adult porn',
 'child sex abus',
 'terror plot',
 'evil attack',
 'sniper',
 'butt',
 'having sex',
 'fatwa',
 'death row',
 '1989 crackdown',
 'brain injuri',
 'terror network',
 'chemical attack',
 'gun and bomb',
 'piss',
 'violent',
 'pressure cooker bomb',
 'butt-hol',
 'pro-choic',
 'police shoot',
 'shoot and kil',
 'rubber bullet',
 'white supremaci',
 'neo-nazi',
 'marijuana',
 'deadliest attack',
 'espionage and intellig',
 'britain first',
 'synthetic drug',
 'racial injustic',
 'counter-terror',
 'mosul',
 'war crim',
 'mass stab',
 'killer',
 'thug',
 'dr. ben carson',
 'gun-tot',
 'bomben',
 'topless',
 'september 11 attack',
 'weapons-grad',
 'attack',
 'shooting suspect',
 'walkout',
 'nigerian terrorist',
 'retaliatory attack',
 'civilian casualti',
 'ammo',
 'world war ii',
 'smoke bomb',
 'racial viol',
 'sword',
 'islamist attack',
 'opioid',
 'gun law',
 'drug leg',
 'crackdown',
 'beirut explos',
 'civil right',
 'bombshel',
 'alleged shoot',
 'online harass',
 'parkland shoot',
 'gaza war',
 'sotloff',
 'snowden',
 'machine-gun',
 'suicide vest',
 'british american tobacco',
 'gunned down',
 'war-torn',
 'death',
 'george floyd death',
 'prisoners of war',
 'act of terror',
 'shot and injur',
 'nuclear d',
 'racial discrimin',
 'handling protest',
 'march for our l',
 'concealed weapon',
 'shooting victim',
 'rebel',
 'hiv',
 'massive march',
 'rape',
 'strip club',
 'combat aircraft',
 'wound',
 'gun shot',
 'church attack',
 'synagogue shoot',
 'bombing campaign',
 'bomb',
 'fecal',
 'charlie hebdo shoot',
 'american university of afghanistan',
 'reich',
 'sex traffick',
 'naked pictur',
 'stun gun',
 'ethnic cleans',
 'blackout tuesday',
 'water cannon',
 'free speech',
 'bombardi',
 'jihadist',
 'oral sex',
 'syrian attack',
 'national guard',
 'hiroshima',
 'sexual',
 'bomb threat',
 'social unrest',
 'nuclear',
 'orgasm',
 'gun-point',
 'crowd',
 'dead bodi',
 'mass shoot',
 'violent protest',
 'explosive devic',
 'global death tol',
 'dangerous weapon',
 'automated execut',
 'farc',
 'consenting adult',
 'dyke',
 'pornographi',
 '2001 attack',
 'lsd',
 'petrol bomb',
 'terror group',
 'far right',
 'racism',
 'ghb',
 'porn',
 'sexual alleg',
 'racial',
 'shooter',
 'alcohol abus',
 'naked photo',
 'guerrilla',
 'ahmaud arberi',
 'hustler',
 'brandishing gun',
 'blacklivesmatt',
 'kidnapp',
 'fascist',
 'same-sex marriag',
 'shotgun',
 'pulled a gun',
 'shot and wound',
 'alcoholic beverag',
 'vagina',
 'roadside bomb',
 'veteran',
 'racial segreg',
 'attacks in fr',
 'cunt',
 'smoking addict',
 'ambush',
 'bomber',
 'racist com',
 'nuclear arm',
 'consent',
 'molotov cocktail',
 'abusive tweet',
 'high school shoot',
 'shooting spre',
 'anthrax',
 'bitch',
 'military mobilis',
 'string of attack',
 'terrorist attack',
 'city bomb',
 'stabbing attack',
 'misogyni',
 'covid-19 death',
 '9/11 attack',
 'al-qaeda',
 'uterus',
 'driving under th',
 'terror threat',
 'military escal',
 'missile launch',
 'pot',
 'joint strike fight',
 'period',
 'armament',
 'saudi attack',
 'adult film',
 'military exercis',
 'bank of america merrill lynch',
 'injuri',
 'fascism',
 'inciting viol',
 'blunt',
 'nightclub shoot',
 'gun right',
 'improvised explosive devic',
 'nuclear bomb',
 'nuclear test',
 '#blacklivesmatt',
 'casualti',
 'chris coon',
 'sexual encount',
 'coup',
 'air attack',
 'random shoot',
 'military oper',
 'son of a bitch',
 'antisemit',
 'soldier shot',
 'bullet',
 'lgbt',
 'viagra',
 'swastika',
 'lynch',
 'anorexia',
 'counterterror',
 'pedophilia',
 'ejacul',
 'police attack',
 'insurrection act',
 'gunshot',
 'weapons of war',
 'boko',
 'tobacco',
 'gun control',
 'tragic shoot',
 'kill',
 'drug addict',
 'cyber attack',
 'fertil',
 'multiple dead',
 'nice attack',
 'far-right',
 'home-made bomb',
 'psilocybin',
 'biological weapon',
 'gun attack',
 'newtown',
 'instabl',
 'ricin',
 'condemned the attack',
 'covid death',
 'condom',
 'pedophil',
 'gun drawn',
 'concentration camp',
 'dui',
 'suspected shoot',
 'coupon',
 'pistol',
 'racismo',
 'black lives matt',
 'std',
 'protests and demonstr',
 'shot dead',
 'shooting rampag',
 'bioterror',
 'anti-semit',
 'auschwitz',
 'alcohol poison',
 'bloodbath',
 'raqqa',
 'ferguson',
 'paris attack',
 'jihadi john',
 'killer virus',
 'carrier strike group',
 'rapist',
 'oxycontin',
 'shoot up',
 'racially abus',
 'unrest',
 'abuse hotlin',
 'abortion bil',
 'fetus',
 'hunting/shoot',
 'racism in america',
 'suppress',
 'suffoc',
 'missile attack',
 'gun',
 'reach around',
 'terrorist',
 'anti-lgbt',
 'assault weapon',
 'military opt',
 'suicide bomb',
 'breonna taylor',
 'arsonist',
 'foreplay',
 'racist abus',
 'bomb scar',
 'total death',
 'hijack',
 'molest',
 'a shoot',
 'sandy hook',
 'hitler',
 'protest',
 'sex',
 'bomb blast',
 'attack in london',
 'racist tweet',
 'gunman opened fir',
 'soldier',
 'wildfire death',
 'smuggl',
 'jihad',
 'shoot him',
 'cum',
 'vegas gunman',
 'suicide attack',
 'food and drug administr',
 'alt right',
 'bomb-mak',
 'female genital mutil',
 'offensive weapon',
 'queer',
 'domestic terrorist',
 'racial inequ',
 'slaughter',
 'sean spic',
 'child molest',
 'suicide blast',
 'mdma',
 'tampon',
 'sex assault',
 'drunk-driv',
 'boycott',
 'bahamas storm',
 'gun went off',
 'osama bin laden',
 'cyber-attack',
 'vietnam war',
 'war on terror']

In [29]:
len(bad_words)

765

In [30]:
bad_words = re.compile('|'.join(bad_words))   
mask = ((db_before['title'].str.contains(bad_words))|(db_before['description'].str.contains(bad_words))|(db_before['tags'].str.contains(bad_words)))
db_before['bad_words']=mask
db_before['bad_words']=db_before['bad_words'].fillna('None')

C:\Users\mrass\AppData\Local\Temp\ipykernel_22312\207782909.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db_before['bad_words']=mask
C:\Users\mrass\AppData\Local\Temp\ipykernel_22312\207782909.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db_before['bad_words']=db_before['bad_words'].fillna('None')

In [31]:
db_before

,Unnamed: 0.1,Unnamed: 0,category,channel,date_crawled,description,id,duration,tags,title,upload,week,before_updates,bad_words
363,492,758,Gaming,UCzWfqsjlvzAOUozsGFR3kbg,2019-10-31 15:41:09.131833,Opening a 10 out of 10 clan chest on clash roy...,bBV59R_eTdE,825,"clash royale,clash royal,clash royale clan che...",OPENING ''10 OUT OF 10'' CLAN CHEST :: Clash R...,2017-03-19,2017-11,1.0,False
364,493,759,Gaming,UCzWfqsjlvzAOUozsGFR3kbg,2019-10-31 15:41:09.789859,My first legendary card to level 4 on clash ro...,1Br91TiCbys,728,"clash royale,clash royal,clash royale legeneda...",MY FIRST ''LEVEL 4'' LEGENDARY CARD :: Clash R...,2017-03-19,2017-11,1.0,False
365,494,760,Gaming,UCzWfqsjlvzAOUozsGFR3kbg,2019-10-31 15:41:10.468107,Opening all chests from every arena in clash r...,9zAf3WP2DSU,844,"clash royale,clash royal,clash royale chest op...",ALL ARENA CHESTS OPENING :: Clash Royale :: SU...,2017-03-18,2017-11,1.0,False
366,495,761,Gaming,UCzWfqsjlvzAOUozsGFR3kbg,2019-10-31 15:41:11.149710,clash royale 12 wins battle deck tips for clas...,VKFYt3w2fmI,895,"clash royale,clash royal,clash royale bandit,c...",12 WINS ''BANDIT CHALLENGE'' STRATEGY :: Clash...,2017-03-16,2017-11,1.0,False
367,496,762,Gaming,UCzWfqsjlvzAOUozsGFR3kbg,2019-10-31 15:41:11.848939,Clash Royale super magical chest challenge wit...,zFmq8YnW904,1029,"clash royale,clash royal,clash royale super ma...",SUPER MAGICAL CHEST CHALLENGE :: Clash Royale ...,2017-03-16,2017-11,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11845902,18698504,2370653,Entertainment,UCrxp18MtcilHK3o8n5aHBUA,2019-11-19 15:14:16.842404,Here's Part 1 of Lauren and Simone's Biggest S...,xpy-MGNxvw8,111,NaN,Lauren and Simone's Biggest Sequel Ever Part 1,2016-08-15,2016-33,1.0,False
11845903,18698505,2370654,Entertainment,UCrxp18MtcilHK3o8n5aHBUA,2019-11-19 15:14:17.418930,Taken From Tigger's StoryTime.,QLAPESq6oe8,33,NaN,Tigger's Clues Notebook Drawings Season 1 Ep 4,2016-08-15,2016-33,1.0,False
11845904,18698506,2370655,Entertainment,UCrxp18MtcilHK3o8n5aHBUA,2019-11-19 15:14:17.998324,I created this video with the YouTube Slidesho...,aEdyQCDmWo4,3,NaN,Do You Have This VHS? #14,2016-08-15,2016-33,1.0,False
11845921,18699096,2373436,Travel & Events,UCrxOaESt4w_XZUFTs-lMeBg,2019-11-04 05:03:34.043623,Thank you for watching my 18th birthday haul! ...,uUM4a_ylcCo,527,"Haul,Makeup,Tutorial,18,Pug,Fenty Puma,Slides,...",18TH BIRTHDAY HAUL,2017-03-04,2017-09,1.0,False
11845922,18699097,2373437,Travel & Events,UCrxOaESt4w_XZUFTs-lMeBg,2019-11-04 05:03:34.590691,HAPPY HALLOWEEN!\nHello & thank you for watchi...,GZ8OnC6su5Y,662,"halloween,halloween makeup,makeup tutorial,blo...",HALLOWEEN MAKEUP | BLOODY NURSE,2016-10-25,2016-43,1.0,False

In [37]:
db_before['bad_words'].value_counts()

bad_words
True     1480615
False    1261780
Name: count, dtype: int64

In [38]:
db_channels=db_before.groupby(['channel','bad_words'], as_index=False).size()
db_channels

                        channel  bad_words  size
0      UC--24Q3_ZQeFmgJE-Um5QZQ      False     3
1      UC--24Q3_ZQeFmgJE-Um5QZQ       True    28
2      UC--2EbuIuBOGgGqPiJxi3rg      False     5
3      UC--3ozenTzry39-xMqAPQlw      False     3
4      UC--3ozenTzry39-xMqAPQlw       True     4
...                         ...        ...   ...
91422  UCzzt-UNlRHbEFY3rEpFpuXw      False    10
91423  UCzzt-UNlRHbEFY3rEpFpuXw       True     1
91424  UCzzzPMh9fZHxc7gxPRB2LHQ      False    41
91425  UCzzzPMh9fZHxc7gxPRB2LHQ       True   121
91426  UCzzzZ3-icktxbC3j7hkWqRw       True     1

[91427 rows x 3 columns]

In [39]:
db_cha_bad=pd.crosstab(db_before['channel'],db_before['bad_words'], margins=True)
db_cha_bad

bad_words                   False     True      All
channel
UC--24Q3_ZQeFmgJE-Um5QZQ        3       28       31
UC--2EbuIuBOGgGqPiJxi3rg        5        0        5
UC--3ozenTzry39-xMqAPQlw        3        4        7
UC--6E6EpybocdaNlPhvK_9A        4        0        4
UC--70ql_IxJmhmqXqrkJrWQ        6       27       33
...                           ...      ...      ...
UCzzqd0yx7h1PuC3KJVqeJgw       66       11       77
UCzzt-UNlRHbEFY3rEpFpuXw       10        1       11
UCzzzPMh9fZHxc7gxPRB2LHQ       41      121      162
UCzzzZ3-icktxbC3j7hkWqRw        0        1        1
All                       1261780  1480615  2742395

[51860 rows x 3 columns]

In [41]:
db_cha_bad['percentage_true']=round((db_cha_bad[True]/db_cha_bad['All'])*100)

conditions=[(db_cha_bad['percentage_true']<=0),
            (db_cha_bad['percentage_true']>0)]
values=['Control','Treatment']

db_cha_bad['type_channel_0']=np.select(conditions, values)

db_cha_bad

bad_words,False,True,All,percentage_true,type_channel_0
channel,,,,,
UC--24Q3_ZQeFmgJE-Um5QZQ,3,28,31,90.0,Treatment
UC--2EbuIuBOGgGqPiJxi3rg,5,0,5,0.0,Control
UC--3ozenTzry39-xMqAPQlw,3,4,7,57.0,Treatment
UC--6E6EpybocdaNlPhvK_9A,4,0,4,0.0,Control
UC--70ql_IxJmhmqXqrkJrWQ,6,27,33,82.0,Treatment
...,...,...,...,...,...
UCzzqd0yx7h1PuC3KJVqeJgw,66,11,77,14.0,Treatment
UCzzt-UNlRHbEFY3rEpFpuXw,10,1,11,9.0,Treatment
UCzzzPMh9fZHxc7gxPRB2LHQ,41,121,162,75.0,Treatment
UCzzzZ3-icktxbC3j7hkWqRw,0,1,1,100.0,Treatment
All,1261780,1480615,2742395,54.0,Treatment

In [42]:
conditions=[(db_cha_bad['percentage_true']<=10),
            (db_cha_bad['percentage_true']>10)]
values=['Control','Treatment']

db_cha_bad['type_channel_10']=np.select(conditions, values)

db_cha_bad

bad_words,False,True,All,percentage_true,type_channel_0,type_channel_10
channel,,,,,,
UC--24Q3_ZQeFmgJE-Um5QZQ,3,28,31,90.0,Treatment,Treatment
UC--2EbuIuBOGgGqPiJxi3rg,5,0,5,0.0,Control,Control
UC--3ozenTzry39-xMqAPQlw,3,4,7,57.0,Treatment,Treatment
UC--6E6EpybocdaNlPhvK_9A,4,0,4,0.0,Control,Control
UC--70ql_IxJmhmqXqrkJrWQ,6,27,33,82.0,Treatment,Treatment
...,...,...,...,...,...,...
UCzzqd0yx7h1PuC3KJVqeJgw,66,11,77,14.0,Treatment,Treatment
UCzzt-UNlRHbEFY3rEpFpuXw,10,1,11,9.0,Treatment,Control
UCzzzPMh9fZHxc7gxPRB2LHQ,41,121,162,75.0,Treatment,Treatment
UCzzzZ3-icktxbC3j7hkWqRw,0,1,1,100.0,Treatment,Treatment
All,1261780,1480615,2742395,54.0,Treatment,Treatment

In [43]:
conditions=[(db_cha_bad['percentage_true']<=25),
            (db_cha_bad['percentage_true']>25)]
values=['Control','Treatment']

db_cha_bad['type_channel_25']=np.select(conditions, values)

db_cha_bad

bad_words,False,True,All,percentage_true,type_channel_0,type_channel_10,type_channel_25
channel,,,,,,,
UC--24Q3_ZQeFmgJE-Um5QZQ,3,28,31,90.0,Treatment,Treatment,Treatment
UC--2EbuIuBOGgGqPiJxi3rg,5,0,5,0.0,Control,Control,Control
UC--3ozenTzry39-xMqAPQlw,3,4,7,57.0,Treatment,Treatment,Treatment
UC--6E6EpybocdaNlPhvK_9A,4,0,4,0.0,Control,Control,Control
UC--70ql_IxJmhmqXqrkJrWQ,6,27,33,82.0,Treatment,Treatment,Treatment
...,...,...,...,...,...,...,...
UCzzqd0yx7h1PuC3KJVqeJgw,66,11,77,14.0,Treatment,Treatment,Control
UCzzt-UNlRHbEFY3rEpFpuXw,10,1,11,9.0,Treatment,Control,Control
UCzzzPMh9fZHxc7gxPRB2LHQ,41,121,162,75.0,Treatment,Treatment,Treatment
UCzzzZ3-icktxbC3j7hkWqRw,0,1,1,100.0,Treatment,Treatment,Treatment
All,1261780,1480615,2742395,54.0,Treatment,Treatment,Treatment

In [ ]:
db_cha_bad

In [45]:
db_cha_bad.to_csv('channel_cat_ada.csv', sep=';')