In [1]:
import pandas as pd
import numpy as np

## Regrouping data per weeks

In [2]:
db_video=pd.read_csv('weekly_uploads_cat_completed.csv', sep=';')
db_video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3372705 entries, 0 to 3372704
Data columns (total 7 columns):
 #   Column         Dtype
---  ------         -----
 0   Unnamed: 0     int64
 1   channel        object
 2   week           object
 3   id_0           int64
 4   main_cat       object
 5   before_update  int64
 6   subs           float64
dtypes: float64(1), int64(3), object(3)
memory usage: 180.1+ MB

In [3]:
# videos published after 1st content moderation update
condition=[(db_video["week"]>="2017-12"),
          (db_video["week"]<"2017-12")]
value=[1, 0]
db_video["first_moderation_update"]=np.select(condition, value)

In [4]:
db_video

,Unnamed: 0,channel,week,id_0,main_cat,before_update,subs,first_moderation_update
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1873.0,0
1,1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1873.0,0
2,2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1873.0,0
3,3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1873.0,0
4,4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1873.0,0
...,...,...,...,...,...,...,...,...
3372700,3630937,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0,18966.0,1
3372701,3630938,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0,18966.0,1
3372702,3630939,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0,18966.0,1
3372703,3630940,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0,18966.0,1
3372704,3630941,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0,18966.0,1

In [5]:
db_video['week']=db_video['week'].replace('2017-00', '2016-52')

In [6]:
db_video

,Unnamed: 0,channel,week,id_0,main_cat,before_update,subs,first_moderation_update
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,1,Travel,1,1873.0,0
1,1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,1,Travel,1,1873.0,0
2,2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,1,Travel,1,1873.0,0
3,3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,1,Travel,1,1873.0,0
4,4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,1,Travel,1,1873.0,0
...,...,...,...,...,...,...,...,...
3372700,3630937,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,0,How to & Style,0,18966.0,1
3372701,3630938,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,0,How to & Style,0,18966.0,1
3372702,3630939,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,0,How to & Style,0,18966.0,1
3372703,3630940,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,0,How to & Style,0,18966.0,1
3372704,3630941,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,0,How to & Style,0,18966.0,1

In [7]:
db_weekly=db_video.groupby(['channel', 'week', 
                           'first_moderation_update'],
                           as_index=False, 
                           dropna=False)['id_0'].sum(min_count=1)
db_weekly

                          channel     week  first_moderation_update  id_0
0        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-33                        0     1
1        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-34                        0     1
2        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-35                        0     1
3        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-36                        0     1
4        UC--24Q3_ZQeFmgJE-Um5QZQ  2016-37                        0     1
...                           ...      ...                      ...   ...
3372700  UCzzzZ3-icktxbC3j7hkWqRw  2017-39                        1     0
3372701  UCzzzZ3-icktxbC3j7hkWqRw  2017-40                        1     0
3372702  UCzzzZ3-icktxbC3j7hkWqRw  2017-41                        1     0
3372703  UCzzzZ3-icktxbC3j7hkWqRw  2017-42                        1     0
3372704  UCzzzZ3-icktxbC3j7hkWqRw  2017-43                        1     0

[3372705 rows x 4 columns]

In [8]:
db_weekly[db_weekly['week']=='2016-52']

                          channel     week  first_moderation_update  id_0
19       UC--24Q3_ZQeFmgJE-Um5QZQ  2016-52                        0     1
82       UC--2EbuIuBOGgGqPiJxi3rg  2016-52                        0     0
145      UC--3ozenTzry39-xMqAPQlw  2016-52                        0     0
208      UC--6E6EpybocdaNlPhvK_9A  2016-52                        0     0
271      UC--70ql_IxJmhmqXqrkJrWQ  2016-52                        0     1
...                           ...      ...                      ...   ...
3372409  UCzzoJY_ln_StRVdrRX1_ftg  2016-52                        0     0
3372472  UCzzqd0yx7h1PuC3KJVqeJgw  2016-52                        0     1
3372535  UCzzt-UNlRHbEFY3rEpFpuXw  2016-52                        0     1
3372598  UCzzzPMh9fZHxc7gxPRB2LHQ  2016-52                        0    12
3372661  UCzzzZ3-icktxbC3j7hkWqRw  2016-52                        0     0

[53535 rows x 4 columns]

#### Adding channels informations

In [9]:
db_treat=pd.read_csv('id_channels_treatment_0.csv', sep=';')
db_treat

       Unnamed: 0                id_channel       type
0               0  UC--MxpGXJ3LVD8KvlNzRlcA  treatment
1               1  UC--szL7ECbL2jmnOpx6BrNg  treatment
2               2  UC-0CzRZeML8zw4pFTVDq65Q  treatment
3               3  UC-0Wg1wOUp-bRF1ZiC0dE8g  treatment
4               4  UC-1b52dI6MuR5BNLQj2FvFg  treatment
...           ...                       ...        ...
20842       20842  UCzvmBKjsw19OY5RBauMtVpA  treatment
20843       20843  UCzwl3WOpGBUoy6bbyV9Bpyg  treatment
20844       20844  UCzxLOMj3HTM4yKGNtaG34-Q  treatment
20845       20845  UCzyfkcDsgePLd09B-8LxX0g  treatment
20846       20846  UCzyhU6QP4_HRLR1aoyRg1ow  treatment

[20847 rows x 3 columns]

In [10]:
db_weekly=pd.merge(db_weekly, db_treat, how='left', left_on='channel', right_on='id_channel')
db_weekly

,channel,week,first_moderation_update,id_0,Unnamed: 0,id_channel,type
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,16797.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,16797.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,16797.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,16797.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,16797.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment

In [11]:
db_weekly=db_weekly.drop(['Unnamed: 0', 'id_channel'],
            axis=1)

In [12]:
db_treat=pd.read_csv('id_channels_treatment_10.csv', sep=';')
db_treat

      Unnamed: 0                id_channel       type
0              0  UC--MxpGXJ3LVD8KvlNzRlcA  treatment
1              1  UC--szL7ECbL2jmnOpx6BrNg  treatment
2              2  UC-2daqAolwaOiFiLdNz31Kg  treatment
3              3  UC-7HtwLZzpdC6jdGl21QukQ  treatment
4              4  UC-RvpobOmrGvg57zSOrbRCQ  treatment
...          ...                       ...        ...
5275        5275  UCzmoXWDBrbeYgZ_JGrGjqxw  treatment
5276        5276  UCznS4Pk3VcTIfDUuWrQtdzQ  treatment
5277        5277  UCzpQlPzEF117cTHhhnzSbXg  treatment
5278        5278  UCzusrs6aDzKs9mfAWf9SG9g  treatment
5279        5279  UCzxztcLww-jPvE5QbFC3n0g  treatment

[5280 rows x 3 columns]

In [13]:
db_weekly=pd.merge(db_weekly, db_treat, how='left', left_on='channel', right_on='id_channel')
db_weekly

,channel,week,first_moderation_update,id_0,type_x,Unnamed: 0,id_channel,type_y
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,3908.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,3908.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,3908.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,3908.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,3908.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment

In [14]:
db_weekly=db_weekly.drop(['Unnamed: 0', 'id_channel'],
            axis=1)

In [15]:
db_treat=pd.read_csv('id_channels_treatment_25.csv', sep=';')
db_treat

      Unnamed: 0                id_channel       type
0              0  UC--szL7ECbL2jmnOpx6BrNg  treatment
1              1  UC-fYwtJ86cOL9LwOd39aLnA  treatment
2              2  UC-wWHzOQHabyEMj7T49J1aw  treatment
3              3  UC-y2mkf95VCf5zjEzigiVDw  treatment
4              4  UC04ZW2FS8RfUmJEa39_-JoA  treatment
...          ...                       ...        ...
1901        1901  UCzAJMmlolVXnzXZVU7rlbfQ  treatment
1902        1902  UCzgtrerHnlLSeb6-lAN-fFg  treatment
1903        1903  UCzmoXWDBrbeYgZ_JGrGjqxw  treatment
1904        1904  UCznS4Pk3VcTIfDUuWrQtdzQ  treatment
1905        1905  UCzusrs6aDzKs9mfAWf9SG9g  treatment

[1906 rows x 3 columns]

In [16]:
db_weekly=pd.merge(db_weekly, db_treat, how='left', left_on='channel', right_on='id_channel')
db_weekly

,channel,week,first_moderation_update,id_0,type_x,type_y,Unnamed: 0,id_channel,type
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,1333.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,1333.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,1333.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,1333.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,1333.0,UCzzzZ3-icktxbC3j7hkWqRw,treatment

In [17]:
db_weekly=db_weekly.drop(['Unnamed: 0', 'id_channel'],
            axis=1)

In [18]:
db_weekly.rename(columns={'type_x':'type_0', 
                         'type_y':'type_10', 
                         'type':'type_25'}, inplace=True)

In [19]:
db_weekly.head()

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN

In [20]:
db_out=pd.read_csv('outliers_995.csv', sep=';')
db_out

,...1,channel,week,id_0,main_cat,before_update,subs
0,3606,UC-2Y8dQb0S6DtpxNgAKoJKA,2016-48,83,Gaming,1,5173029
1,3634,UC-2Y8dQb0S6DtpxNgAKoJKA,2017-24,78,Gaming,0,5173029
2,3643,UC-2Y8dQb0S6DtpxNgAKoJKA,2017-33,46,Gaming,0,5173029
3,3644,UC-2Y8dQb0S6DtpxNgAKoJKA,2017-34,52,Gaming,0,5173029
4,11706,UC-C-xE8jsjKsBrHkFrxDBCw,2017-32,51,Education,0,2348
...,...,...,...,...,...,...,...
16331,3611077,UCze69pfIVefPW41h65eh8lQ,2017-24,74,Education,0,23351
16332,3615746,UCzjc5u-yPodS9U9E4tpNRUw,2017-31,50,Gaming,0,1712
16333,3619291,UCzn9oVj62EFaJHjQcohwbmg,2016-37,44,Science & Technology,1,6387
16334,3620135,UCzo1KeoL1qH0IwxcQMN8xxQ,2017-10,39,Autos & Vehicles,1,1797
16335,3623262,UCzrskTiT_ObAk3xBkVxMz5g,2016-39,40,Science & Technology,1,8714

In [21]:
db_weekly=db_weekly[~db_weekly['channel'].isin(db_out['channel'])]
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment

In [22]:
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,NaN,NaN,NaN
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,NaN,NaN,NaN
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,NaN,NaN,NaN
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,NaN,NaN,NaN
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment

In [23]:
db_weekly['type_0'] = db_weekly['type_0'].fillna('control')
db_weekly['type_10'] = db_weekly['type_10'].fillna('control')
db_weekly['type_25'] = db_weekly['type_25'].fillna('control')

db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control
...,...,...,...,...,...,...,...
3372700,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment
3372701,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment
3372702,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment
3372703,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment
3372704,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment

In [24]:
db_weekly['type_0'].value_counts()

type_0
control      1986768
treatment    1280349
Name: count, dtype: int64

In [25]:
db_chan_ada = pd.read_csv('channel_cat_ada.csv', sep=';')
db_chan_ada

,channel,False,True,All,percentage_true,type_channel_0,type_channel_10,type_channel_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,3,28,31,90.0,Treatment,Treatment,Treatment
1,UC--2EbuIuBOGgGqPiJxi3rg,5,0,5,0.0,Control,Control,Control
2,UC--3ozenTzry39-xMqAPQlw,3,4,7,57.0,Treatment,Treatment,Treatment
3,UC--6E6EpybocdaNlPhvK_9A,4,0,4,0.0,Control,Control,Control
4,UC--70ql_IxJmhmqXqrkJrWQ,6,27,33,82.0,Treatment,Treatment,Treatment
...,...,...,...,...,...,...,...,...
51855,UCzzqd0yx7h1PuC3KJVqeJgw,66,11,77,14.0,Treatment,Treatment,Control
51856,UCzzt-UNlRHbEFY3rEpFpuXw,10,1,11,9.0,Treatment,Control,Control
51857,UCzzzPMh9fZHxc7gxPRB2LHQ,41,121,162,75.0,Treatment,Treatment,Treatment
51858,UCzzzZ3-icktxbC3j7hkWqRw,0,1,1,100.0,Treatment,Treatment,Treatment
51859,All,1261780,1480615,2742395,54.0,Treatment,Treatment,Treatment

In [26]:
db_weekly=pd.merge(db_weekly, db_chan_ada, how='left', left_on='channel', right_on='channel')
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,percentage_true,type_channel_0,type_channel_10,type_channel_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment

In [28]:
db_weekly=db_weekly.drop(['Unnamed: 0', 'False', 'True', 'All'],
            axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [29]:
db_chan_cat=pd.read_csv('channel_cat_51.csv', sep=';')
db_chan_cat

       Unnamed: 0                   channel        main_cat
0               0  UC--24Q3_ZQeFmgJE-Um5QZQ          Travel
1               1  UC--2EbuIuBOGgGqPiJxi3rg          People
2               2  UC--3ozenTzry39-xMqAPQlw       Education
3               3  UC--6E6EpybocdaNlPhvK_9A          People
4               4  UC--70ql_IxJmhmqXqrkJrWQ          People
...           ...                       ...             ...
88488       88488  UCzzqd0yx7h1PuC3KJVqeJgw          People
88489       88489  UCzzsKg4jPGBL05t2w3HfHBA           Mixed
88490       88490  UCzzt-UNlRHbEFY3rEpFpuXw   Entertainment
88491       88491  UCzzzPMh9fZHxc7gxPRB2LHQ           Mixed
88492       88492  UCzzzZ3-icktxbC3j7hkWqRw  How to & Style

[88493 rows x 3 columns]

In [30]:
db_weekly=pd.merge(db_weekly, db_chan_cat, how='left', left_on='channel', right_on='channel')
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,percentage_true,type_channel_0,type_channel_10,type_channel_25,Unnamed: 0,main_cat
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,0,Travel
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,0,Travel
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,0,Travel
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,0,Travel
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,0,Travel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,88492,How to & Style
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,88492,How to & Style
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,88492,How to & Style
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,88492,How to & Style
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,88492,How to & Style

In [31]:
db_timeseries=pd.read_csv("timeseries_cleaned.csv", sep=';')
db_timeseries

,Unnamed: 0,channel,category,datetime,views,delta_views,subs,delta_subs,videos,delta_videos,activity,week
0,0,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-03 00:00:00,2.024946e+05,0.000000,650.222222,0.000000,5,0,3,2017-27
1,1,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-10 00:00:00,3.940857e+05,191591.111111,1046.000000,395.777778,6,1,1,2017-28
2,2,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-17 00:00:00,8.353938e+05,441308.083333,1501.500000,455.500000,6,0,1,2017-29
3,3,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-24 00:00:00,1.104577e+06,269183.250000,1750.000000,248.500000,6,0,0,2017-30
4,4,UCBJuEqXfXTdcPSbGO9qqn1g,Film and Animation,2017-07-31 00:00:00,1.284406e+06,179828.600000,2008.300000,258.300000,6,0,0,2017-31
...,...,...,...,...,...,...,...,...,...,...,...,...
13878018,18872455,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-02 23:00:00,3.167820e+03,159.564033,1490.027778,0.000000,0,0,0,2018-48
13878019,18872456,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-09 23:00:00,3.327384e+03,159.564033,1484.509259,0.000000,0,0,0,2018-49
13878020,18872457,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-16 23:00:00,3.486948e+03,159.564033,1473.620370,0.000000,0,0,0,2018-50
13878021,18872458,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-23 23:00:00,3.646512e+03,159.564033,1470.013889,0.000000,0,0,0,2018-51
13878022,18872459,UC0UeVA9YHpOEr_Ng442xiRw,Gaming,2018-12-30 23:00:00,3.806076e+03,159.564033,1717.935185,247.921296,0,0,0,2018-52

In [32]:
db_weekly=pd.merge(db_weekly, db_timeseries, how='left', left_on=['channel', 'week'], right_on=['channel', 'week'])

In [33]:
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,...,Unnamed: 0_y,category,datetime,views,delta_views,subs,delta_subs,videos,delta_videos,activity
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,...,1928794.0,Travel & Events,2016-08-15 00:00:00,69982.000,2381.750,1530.750,22.125,31.0,1.0,2.0
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,...,1928795.0,Travel & Events,2016-08-22 00:00:00,72663.125,2681.125,1558.625,27.875,32.0,1.0,2.0
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,...,1928796.0,Travel & Events,2016-08-29 00:00:00,75093.000,2429.875,1591.000,32.375,33.0,1.0,2.0
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,...,1928797.0,Travel & Events,2016-09-05 00:00:00,77511.500,2418.500,1621.625,30.625,34.0,1.0,2.0
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,...,1928798.0,Travel & Events,2016-09-12 00:00:00,80095.000,2583.500,1650.750,29.125,35.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,...,3932834.0,Howto & Style,2017-09-25 00:00:00,3996798.000,50051.750,53927.000,413.875,37.0,0.0,0.0
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,...,3932835.0,Howto & Style,2017-10-02 00:00:00,4043154.625,46356.625,54334.750,407.750,37.0,0.0,0.0
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,...,3932836.0,Howto & Style,2017-10-09 00:00:00,4095563.000,52408.375,54783.000,448.250,37.0,0.0,0.0
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,...,3932837.0,Howto & Style,2017-10-16 00:00:00,4149823.125,54260.125,55273.625,490.625,37.0,0.0,0.0
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,...,3932838.0,Howto & Style,2017-10-23 00:00:00,4202399.000,52575.875,55758.000,484.375,37.0,0.0,0.0

In [34]:
db_weekly=db_weekly.drop(['Unnamed: 0_x', 'Unnamed: 0_y', 'views', 'delta_views', 'delta_subs', 'videos',
                         'delta_videos', 'activity'],
            axis=1)

In [35]:
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,percentage_true,type_channel_0,type_channel_10,type_channel_25,main_cat,category,datetime,subs
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,Travel,Travel & Events,2016-08-15 00:00:00,1530.750
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,Travel,Travel & Events,2016-08-22 00:00:00,1558.625
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,Travel,Travel & Events,2016-08-29 00:00:00,1591.000
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,Travel,Travel & Events,2016-09-05 00:00:00,1621.625
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,90.0,Treatment,Treatment,Treatment,Travel,Travel & Events,2016-09-12 00:00:00,1650.750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,How to & Style,Howto & Style,2017-09-25 00:00:00,53927.000
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,How to & Style,Howto & Style,2017-10-02 00:00:00,54334.750
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,How to & Style,Howto & Style,2017-10-09 00:00:00,54783.000
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,How to & Style,Howto & Style,2017-10-16 00:00:00,55273.625
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,100.0,Treatment,Treatment,Treatment,How to & Style,Howto & Style,2017-10-23 00:00:00,55758.000

### Coding dummies

In [36]:
condition=[(db_weekly['type_0']=='control'),
          (db_weekly['type_0']=='treatment')]
value=[0,1]
db_weekly['treated_0']=np.select(condition, value)

condition=[(db_weekly['type_10']=='control'),
          (db_weekly['type_10']=='treatment')]
value=[0,1]
db_weekly['treated_10']=np.select(condition, value)

condition=[(db_weekly['type_25']=='control'),
          (db_weekly['type_25']=='treatment')]
value=[0,1]
db_weekly['treated_25']=np.select(condition, value)

In [37]:
condition=[(db_weekly['type_channel_0']=='Control'),
          (db_weekly['type_channel_0']=='Treatment')]
value=[0,1]
db_weekly['treated_ada_0']=np.select(condition, value)

condition=[(db_weekly['type_channel_10']=='Control'),
          (db_weekly['type_channel_10']=='Treatment')]
value=[0,1]
db_weekly['treated_ada_10']=np.select(condition, value)

condition=[(db_weekly['type_channel_25']=='Control'),
          (db_weekly['type_channel_25']=='Treatment')]
value=[0,1]
db_weekly['treated_ada_25']=np.select(condition, value)

In [38]:
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,...,main_cat,category,datetime,subs,treated_0,treated_10,treated_25,treated_ada_0,treated_ada_10,treated_ada_25
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,...,Travel,Travel & Events,2016-08-15 00:00:00,1530.750,0,0,0,1,1,1
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,...,Travel,Travel & Events,2016-08-22 00:00:00,1558.625,0,0,0,1,1,1
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,...,Travel,Travel & Events,2016-08-29 00:00:00,1591.000,0,0,0,1,1,1
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,...,Travel,Travel & Events,2016-09-05 00:00:00,1621.625,0,0,0,1,1,1
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,...,Travel,Travel & Events,2016-09-12 00:00:00,1650.750,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,...,How to & Style,Howto & Style,2017-09-25 00:00:00,53927.000,1,1,1,1,1,1
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,...,How to & Style,Howto & Style,2017-10-02 00:00:00,54334.750,1,1,1,1,1,1
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,...,How to & Style,Howto & Style,2017-10-09 00:00:00,54783.000,1,1,1,1,1,1
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,...,How to & Style,Howto & Style,2017-10-16 00:00:00,55273.625,1,1,1,1,1,1
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,...,How to & Style,Howto & Style,2017-10-23 00:00:00,55758.000,1,1,1,1,1,1

In [39]:
db_weekly['date_formated']=pd.to_datetime(db_weekly['week']+'0', yearfirst=True, format='%Y-%W%w')

In [40]:
db_weekly

,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,All,...,category,datetime,subs,treated_0,treated_10,treated_25,treated_ada_0,treated_ada_10,treated_ada_25,date_formated
0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,31,...,Travel & Events,2016-08-15 00:00:00,1530.750,0,0,0,1,1,1,2016-08-21
1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,31,...,Travel & Events,2016-08-22 00:00:00,1558.625,0,0,0,1,1,1,2016-08-28
2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,31,...,Travel & Events,2016-08-29 00:00:00,1591.000,0,0,0,1,1,1,2016-09-04
3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,31,...,Travel & Events,2016-09-05 00:00:00,1621.625,0,0,0,1,1,1,2016-09-11
4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,31,...,Travel & Events,2016-09-12 00:00:00,1650.750,0,0,0,1,1,1,2016-09-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,1,...,Howto & Style,2017-09-25 00:00:00,53927.000,1,1,1,1,1,1,2017-10-01
3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,1,...,Howto & Style,2017-10-02 00:00:00,54334.750,1,1,1,1,1,1,2017-10-08
3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,1,...,Howto & Style,2017-10-09 00:00:00,54783.000,1,1,1,1,1,1,2017-10-15
3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,1,...,Howto & Style,2017-10-16 00:00:00,55273.625,1,1,1,1,1,1,2017-10-22
3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,1,...,Howto & Style,2017-10-23 00:00:00,55758.000,1,1,1,1,1,1,2017-10-29

In [41]:
db_weekly['channel'].nunique()

51859

In [42]:
db_weekly.groupby('type_0', as_index=False)['channel'].nunique()

      type_0  channel
0    control    31536
1  treatment    20323

In [43]:
db_weekly.groupby('type_10', as_index=False)['channel'].nunique()

     type_10  channel
0    control    46724
1  treatment     5135

In [44]:
db_weekly.groupby('type_25', as_index=False)['channel'].nunique()

     type_25  channel
0    control    49995
1  treatment     1864

In [45]:
db_weekly.groupby('type_channel_0', as_index=False)['channel'].nunique()

  type_channel_0  channel
0        Control     4056
1      Treatment    47803

In [46]:
db_weekly.groupby('type_channel_10', as_index=False)['channel'].nunique()

  type_channel_10  channel
0         Control     7184
1       Treatment    44675

In [47]:
db_weekly.groupby('type_channel_25', as_index=False)['channel'].nunique()

  type_channel_25  channel
0         Control    14791
1       Treatment    37068

In [48]:
db_video['week'].nunique()

63

In [51]:
db_video['channel'].nunique()

53535

In [49]:
db_video['id_0'].sum()

7807776

In [52]:
db_weekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3267117 entries, 0 to 3267116
Data columns (total 25 columns):
 #   Column                   Dtype
---  ------                   -----
 0   channel                  object
 1   week                     object
 2   first_moderation_update  int32
 3   id_0                     int64
 4   type_0                   object
 5   type_10                  object
 6   type_25                  object
 7   False                    int64
 8   True                     int64
 9   All                      int64
 10  percentage_true          float64
 11  type_channel_0           object
 12  type_channel_10          object
 13  type_channel_25          object
 14  main_cat                 object
 15  category                 object
 16  datetime                 object
 17  subs                     float64
 18  treated_0                int32
 19  treated_10               int32
 20  treated_25               int32
 21  treated_ada_0            int32
 22  treated_ada_10           int32
 23  treated_ada_25           int32
 24  date_formated            datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int32(7), int64(4), object(11)
memory usage: 535.9+ MB

In [53]:
db_weekly.to_csv('true_weekly_uploads_umbalanced_data_ada.csv', sep=';')